# Generated by Django 5.1.4 on 2024-12-21 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_batch_desc_order_status_order_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='name',
        ),
        migrations.AddField(
            model_name='productsize',
            name='size',
            field=models.CharField(choices=[('X-Small', 'XS'), ('Small', 'S'), ('Medium', 'M'), ('Large', 'L'), ('X-Large', 'XL'), ('XX-Large', 'XXL')], default='X-Small', max_length=10),
        ),
    ]
