# Generated by Django 5.1.4 on 2024-12-21 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_productsize_name_productsize_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW_ORDER', 'N'), ('CONFIRMED', 'OK'), ('DISPATCHED', 'D'), ('ON_HOLD', 'H'), ('COMPLETED', 'C'), ('CANCELLED', 'X')], default=('NEW_ORDER', 'N'), max_length=256),
        ),
    ]
