# Generated by Django 5.1.4 on 2024-12-22 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_batchimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
