# Generated by Django 5.1.4 on 2024-12-22 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_order_payment_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'P'), ('SUCCESS', 'S'), ('DENIED', 'D'), ('CANCELLED', 'C')], default=('PENDING', 'P'), max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='store.payment'),
            preserve_default=False,
        ),
    ]
