# Generated by Django 5.1.4 on 2025-01-06 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_cartitem_size_orderitem_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='size',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
    ]
