# Generated by Django 5.1.4 on 2025-01-06 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_cartitem_size_orderitem_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='qunatity',
            new_name='quantity',
        ),
    ]
