# Generated by Django 5.1.4 on 2025-01-08 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_buyer_city_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='address',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='store.buyer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyer',
            name='phone',
            field=models.CharField(default=1, max_length=256, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.buyer'),
        ),
        migrations.AlterField(
            model_name='city',
            name='shipping_charges',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.payment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('NEW_ORDER', 'N'), ('CONFIRMED', 'OK'), ('DISPATCHED', 'D'), ('ON_HOLD', 'H'), ('COMPLETED', 'C'), ('CANCELLED', 'X')], default=('NEW_ORDER', 'N'), max_length=256, null=True),
        ),
    ]
