# Generated by Django 5.1.5 on 2025-02-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_remove_productreview_user_productreview_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='batch_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
