# Generated by Django 5.1.5 on 2025-03-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_batch_batch_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('N', 'NEW_ORDER'), ('OK', 'CONFIRMED'), ('D', 'DISPATCHED'), ('H', 'ON_HOLD'), ('C', 'COMPLETED'), ('X', 'CANCELLED')], default=('N', 'NEW_ORDER'), max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('P', 'PENDING'), ('S', 'SUCCESS'), ('D', 'DENIED'), ('C', 'CANCELLED')], default=('P', 'PENDING'), max_length=256),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(choices=[('X-Small', 'XS'), ('Small', 'S'), ('Medium', 'M'), ('Large', 'L'), ('X-Large', 'XL'), ('XX-Large', 'XXL')], default=('X-Small', 'XS'), max_length=10),
        ),
    ]
