# Generated by Django 5.1.5 on 2025-03-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_payment_shipping_charges_alter_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
